[package]
name = "sonos-cli"
version = "0.1.0"
authors = ["Jordan Doyle <jordan@doyle.la>"]

[dependencies]
sonos = { git = "https://github.com/w4/sonos.rs" }
clap = ""
log = ""
fern = ""
chrono = ""

failure = ""

serde = ""
serde_derive = ""
serde_json = ""

strsim = ""
