[package]
name = "sonos-cli"
version = "0.1.0"
authors = ["Jordan Doyle <jordan@9t9t9.com>"]

[dependencies]
sonos = { path = "../soncon/sonos.rs" }
clap = ""
log = ""
fern = ""
chrono = ""

serde = ""
serde_derive = ""
serde_json = ""
